language: python
python:
  - "3.9"

services:
  - docker


before_script: 
  - pip install docker-compose
  - flake8 --max-line-length 160
script:
  - docker-compose run app sh -c "python manage.py test && flake8 --max-line-length 160"